build:
  version: "{cipher}ced11c56f22cedf35a975d2b516255fcc9e3646385edff03c2bbdec0d4789f8a"
spring:
  datasource:
    url:  jdbc:postgresql://dev-env-postgresql-interview.prod.svc.cluster.local:5442/interviewdb
    username: produser
    password: prodpassword
