notification:
  email: maheshlamichhaneqa048@gmail.com
spring:
  datasource:
    url:  jdbc:postgresql://postgresql-interview.qa.svc.cluster.local:5442/interviewdb
    username: devuser
    password: devpassword
