notification:
  email: maheshlamichhane048@gmail.com
spring:
  datasource:
    url:  jdbc:postgresql://dev-env-postgresql-interview.dev.svc.cluster.local:5442/interviewdb
    username: devuser
    password: "{cipher}60fdcada72c6fc92d71667bb1f2db7275f21440a865c5032e135207f121a5e85"
notification-backend:
  message: "Hey, welcome to the interview dev API."
  contactDetails:
    name: "Pawan Lamichhane - Developer."
    email: "pawanlc@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
