notification:
  email: maheshlamichhaneprod048@gmail.com
spring:
  datasource:
    url:  jdbc:postgresql://prod-env-postgresql-interview.prod.svc.cluster.local:5442/interviewdb
    username: produser
    password: "{cipher}fef1ee8b7d95ea726e9a7e9e6db890b6014660c611c49b01cc69a8192242c0d9"
